version: '3'
# Define services
services:

  # App backend service
  backend-service:
    image: backend:0.0.1-SNAPSHOT # Configuration for building the docker image for the backend service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
        - db-mysql # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/MyAPP?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Database Service (Mysql)
  db-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: MyAPP
      MYSQL_USER: app
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  #------------------------------------------------------------------
  #This definition create the network name `spring-boot-mysql-network`, the two service named `backend-service` and `mysql-service` will bind together with that network.
  #Bridge: The bridge driver creates a private network internal to the host so containers on this network can communicate. External access is granted by exposing ports to containers.
  #Docker secures the network by managing rules that block connectivity between different Docker networks.
  #-------------------------------------------------------------------