export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_SUCCESS="GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE="GET_ARTICLES_FAILURE";

export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_SUCCESS="GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILURE="GET_ARTICLE_FAILURE";

export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const SAVE_ARTICLE_SUCCESS="SAVE_ARTICLE_SUCCESS";
export const SAVE_ARTICLE_FAILURE="SAVE_ARTICLE_FAILURE";

export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_ARTICLE_SUCCESS="UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE="UPDATE_ARTICLE_FAILURE";

export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_SUCCESS="DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILURE="DELETE_ARTICLE_FAILURE";